# Generated by Django 5.0.4 on 2024-05-01 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeInsightApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeMetadata',
            fields=[
                ('anime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=200)),
                ('english_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='English_name', max_length=200, null=True)),
                ('score', models.FloatField(blank=True, db_column='Score', null=True)),
                ('genres', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Genres', max_length=100, null=True)),
                ('synopsis', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Synopsis')),
                ('type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Type', max_length=50, null=True)),
                ('episodes', models.SmallIntegerField(blank=True, db_column='Episodes', null=True)),
                ('aired', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Aired', max_length=50)),
                ('premiered', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Premiered', max_length=50, null=True)),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=50)),
                ('producers', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Producers', max_length=1550, null=True)),
                ('licensors', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Licensors', max_length=100, null=True)),
                ('studios', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Studios', max_length=200, null=True)),
                ('source', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Source', max_length=50, null=True)),
                ('duration', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Duration', max_length=50, null=True)),
                ('age_rating', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Age_Rating', max_length=50, null=True)),
                ('rank', models.IntegerField(blank=True, db_column='Rank', null=True)),
                ('scored_by', models.IntegerField(blank=True, db_column='Scored_By', null=True)),
                ('image_url', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Image_URL', max_length=100)),
            ],
            options={
                'db_table': 'Anime_Metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historywatch',
            fields=[
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historywatch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('userid', models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animename', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AnimeName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist',
                'managed': False,
            },
        ),
    ]
