# Generated by Django 5.0.4 on 2024-05-08 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeInsightApp', '0006_alter_profile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeTensors',
            fields=[
                ('animeid', models.OneToOneField(db_column='AnimeID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AnimeInsightApp.animemetadata')),
                ('tensor_1', models.FloatField()),
                ('tensor_2', models.FloatField()),
                ('tensor_3', models.FloatField()),
                ('tensor_4', models.FloatField()),
                ('tensor_5', models.FloatField()),
                ('tensor_6', models.FloatField()),
                ('tensor_7', models.FloatField()),
                ('tensor_8', models.FloatField()),
                ('tensor_9', models.FloatField()),
                ('tensor_10', models.FloatField()),
                ('tensor_11', models.FloatField()),
                ('tensor_12', models.FloatField()),
                ('tensor_13', models.FloatField()),
                ('tensor_14', models.FloatField()),
                ('tensor_15', models.FloatField()),
                ('tensor_16', models.FloatField()),
            ],
            options={
                'db_table': 'anime_tensors',
                'managed': False,
            },
        ),
    ]
